# Generated by Django 3.1 on 2020-10-22 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='BRDesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='BRName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='VARDesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='VARName',
            new_name='name',
        ),
    ]
