# Generated by Django 3.1 on 2020-09-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDName', models.CharField(max_length=50)),
                ('PRDDescriptions', models.TextField(max_length=1000)),
                ('PRDCreated', models.DateTimeField(auto_now=True)),
                ('PRDPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PRDCost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
