# Generated by Django 3.1 on 2020-09-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200924_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='PRDIImage',
            field=models.ImageField(upload_to='product/', verbose_name='Image'),
        ),
    ]
