# Generated by Django 3.1 on 2020-09-24 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200924_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PRDDescriptions',
            new_name='PRDDesc',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATName', models.CharField(max_length=50)),
                ('CATDesc', models.TextField(max_length=1000, verbose_name='Description')),
                ('CATDImg', models.ImageField(upload_to='category/')),
                ('CATParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
