# Generated by Django 3.1 on 2020-09-24 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200924_0334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Product Alternative', 'verbose_name_plural': 'Product Alternatives'},
        ),
        migrations.DeleteModel(
            name='Product_Alternative',
        ),
    ]
