# Generated by Django 3.1 on 2020-09-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_prdimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATDImg',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATDesc',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
