# Generated by Django 3.1 on 2020-10-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_order_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='PRDOrder',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Order Name '),
        ),
    ]
