# Generated by Django 3.1 on 2020-10-22 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20201023_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category Parent Name'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='accessoriesalternatives',
            field=models.ManyToManyField(related_name='accessories_products', to='product.Product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='accessoriesproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='product.product', verbose_name='Accessories'),
        ),
    ]
