# Generated by Django 3.1 on 2020-10-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20201023_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_accessories',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
