# Generated by Django 3.1 on 2020-10-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_product_accessories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_accessories',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
