# Generated by Django 3.1 on 2020-10-22 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_product_accessories_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_accessories',
            name='title',
        ),
    ]
